name: Setup Sui CLI
description: A composite action that sets up the Sui CLI
inputs:
  version:
    description: The version of the Sui CLI to download
    required: true
  private-key:
    description: The private key to setup for Sui Client
    required: false
    default: ""
  sui-rpc-url:
    description: The RPC URL to setup for Sui Client
    required: false
    default: "https://fullnode.devnet.sui.io:443"

runs:
  using: "composite"
  steps:
    - name: Download Sui CLI
      uses: robinraju/release-downloader@v1.7
      with:
        repository: "MystenLabs/sui"
        tag: ${{ inputs.version }}
        fileName: "sui"
    - name: Setup Sui CLI
      shell: bash
      run: |
        mv ./sui /usr/local/bin
        chmod +x /usr/local/bin/sui

    - name: Setup Sui Client
      shell: bash
      if: ${{ inputs.private-key != '' }}
      env:
        SUI_KEYSTORE_PATH: ~/.sui/sui_config/sui.keystore
        SUI_RPC_URL: ${{ inputs.sui-rpc-url }}
      run: |
        mkdir -p ~/.sui/sui_config
        echo '["${{ inputs.private-key }}"]' > ~/.sui/sui_config/sui.keystore
        export SUI_ACTIVE_ADDRESS=$(sui client addresses --json | jq -r ".[0][0]")
        
        envsubst < .github/sui_cli/client.yaml > ~/.sui/sui_config/client.yaml
