# Registers a VC validator in Eth Relay contract
name: Eth Register Validator
on:
  workflow_dispatch:
    inputs:
      network:
        type: choice
        description: "BSC network name"
        required: true
        default: bsc_testnet
        options:
          - bsc_testnet
          - bsc_mainnet
      validator_address:
        description: "Validator address in BSC network"
        required: true

jobs:
  bsc_register_validator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        working-directory: bsc_mamoru_relay
        run: npm install

      - name: Download publish output
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: eth_publish.yaml
          workflow_conclusion: success
          check_artifacts: true
          name: publish_eth_output
          path: ./bsc_mamoru_relay

      - name: Compile Contracts
        working-directory: bsc_mamoru_relay
        run: | 
          npx hardhat compile
          sleep 5

      - name: Register validator
        working-directory: bsc_mamoru_relay
        env:
          PRIVATE_KEY: ${{ secrets.ETH_MAMORU_PRIVATE_KEY }}
        run: |
          export CONTRACT_ADDRESS=$(cat eth_${{ github.event.inputs.network }}_output.txt | tail -n 1 | tr -d '\n')
          echo "Contract Address:" $CONTRACT_ADDRESS
          echo "Validator Address:" ${{ github.event.inputs.validator_address }}
          echo "Network:" ${{ github.event.inputs.network }}
          echo "npx hardhat register_validator --account ${{ github.event.inputs.validator_address }} --contract ${CONTRACT_ADDRESS} --network ${{ github.event.inputs.network }}"
          npx hardhat register_validator --account "${{ github.event.inputs.validator_address }}" --contract "${CONTRACT_ADDRESS}" --network ${{ github.event.inputs.network }}
