# Deploys Eth Mamoru Relay to the specified network
name: Eth Publish
on:
  workflow_dispatch:
    inputs:
      private_key:
        description: "private key"
        required: true
      network:
        description: "Eth network name"
        required: true
        default: "testnet_bsc"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy
        working-directory: eth_mamoru_relay
        run: |
          set -e -o pipefail
          export PRIVATE_KEY="${{ github.event.inputs.private_key }}"
          npx hardhat run scripts/deploy.ts --network "${{ github.event.inputs.network }}" | tee eth_output.txt

      - uses: actions/upload-artifact@v3
        with:
          name: publish_eth_output
          path: ./eth_mamoru_relay/eth_output.txt
          if-no-files-found: error
