name: ETH Hardhat Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Dependencies
        working-directory: eth_mamoru_relay
        run: npm install

      - name: Compile Contracts and Export ABI
        run: |
          cd eth_mamoru_relay
          npx hardhat export-abi
#          npx hardhat compile

      - name: Run Tests
        run: |
          cd eth_mamoru_relay
          npx hardhat test
