name: EVM Tx Relay Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  # cancel redundant builds on PRs (only on PR, not on branches)
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  evm_tx_relay_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        working-directory: evm_tx_relay
        run: npm install

      - name: Run Tests
        working-directory: evm_tx_relay
        run: npx hardhat test
