# Deploys EVM TX Relay to the specified network
name: EVM Tx Relay Add Address
on:
  workflow_dispatch:
    inputs:
      network:
        type: choice
        description: "Network name"
        required: true
        options:
          - bsc_testnet
          - bsc_mainnet
          - eth_sepolia
          - eth_mainnet
      contract:
        description: "The contract address"
        required: true
      relay-address:
        description: "The relayer address"
        required: true

jobs:
  add_relayer:
    name: "Add relayer"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        working-directory: evm_tx_relay
        run: npm install

      - name: Deploy
        working-directory: evm_tx_relay
        env:
          HARDHAT_PRIVATE_KEY: ${{ secrets.EVM_TX_RELAY_PRIVATE_KEY }}
        run: |
          set -xe
          npx hardhat compile
          npx hardhat --network ${{ github.event.inputs.network }} add-relay-address \
            --contract ${{ github.event.inputs.contract }} \
            --relay-address ${{ github.event.inputs.relay-address }}
